### ISSUE TITLE
Broken!

### ISSUE THREAD

**Issue by mxswd** [joeyadams/hs-acme-year#1]
It does not work anymore!

All my production apps are dying.

**Comment by joeyadams** [comment]
Thanks for the report!  I know acme-year was having issues in several timezones yesterday, but I couldn't reproduce the issue.  Today, I did notice it was broken, strangely enough.

Please upgrade to 2014 and see if that helps.

**Comment by mxswd** [comment]
Excellent, the new version works for me! Thanks!

**Comment by bkirwi** [comment]
Sorry to dig up an old ticket, but this bug seems to have reappeared? Let me know if you need any help reproducing.

**Comment by joeyadams** [comment]
Arrgh, you're right.  I've been busy, but I'll try to get a new version out soon.

Temporary workaround: change the version number to 2015 and recompile.  Newer is better.

**Comment by TimWolla** [comment]
I just came back from holidays and all my production machines stopped working. Please heeeeelp fast.

**Comment by sovietspaceship2** [comment]
My production apps are written in pure functional Haskell without side effects so only today I realised they crashed 8 months ago. I created a pull request to fix the issue, hope it helps.

**Comment by Profpatsch** [comment]
I just now noticed that our critical production log system died about eight months ago and we have serious problems now. Can you please push a fix?!?
